import React, { useState } from 'react';
import { Patient } from '../../types';
import { UserPlus, X, ShieldAlert, HeartPulse } from 'lucide-react';

interface NewPatientModalProps {
  onSavePatient: (patient: Patient) => void;
  onClose: () => void;
}

export const NewPatientModal: React.FC<NewPatientModalProps> = ({ onSavePatient, onClose }) => {
  const [fullName, setFullName] = useState('');
  const [dni, setDni] = useState('');
  const [birthDate, setBirthDate] = useState('1985-05-15');
  const [age, setAge] = useState<number>(41);
  const [gender, setGender] = useState<'M' | 'F' | 'OTRO'>('M');
  const [phone, setPhone] = useState('');
  const [email, setEmail] = useState('');
  const [address, setAddress] = useState('');
  const [bloodType, setBloodType] = useState('O+');
  const [insuranceProvider, setInsuranceProvider] = useState('Particular / Privado');
  const [insurancePolicyNumber, setInsurancePolicyNumber] = useState('');
  const [emergencyContactName, setEmergencyContactName] = useState('');
  const [emergencyContactPhone, setEmergencyContactPhone] = useState('');

  // Safety profile
  const [allergiesStr, setAllergiesStr] = useState('');
  const [creatinineLevel, setCreatinineLevel] = useState<number>(0.9);
  const [eGFR, setEGFR] = useState<number>(90);
  const [hasPacemaker, setHasPacemaker] = useState(false);
  const [hasMetalImplants, setHasMetalImplants] = useState(false);
  const [isPregnantOrPossible, setIsPregnantOrPossible] = useState(false);
  const [hasClaustrophobia, setHasClaustrophobia] = useState(false);
  const [diabeticOnMetformin, setDiabeticOnMetformin] = useState(false);
  const [priorAdverseReactionToContrast, setPriorAdverseReactionToContrast] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!fullName || !dni) return;

    const allergies = allergiesStr
      ? allergiesStr
          .split(',')
          .map(s => s.trim())
          .filter(Boolean)
      : [];

    const cleanDni = dni.trim();
    const autoGeneratedPin = `${Math.floor(1000 + Math.random() * 9000)}`;
    const autoAccessCode = `PAC-${cleanDni.slice(-4)}`;

    const newPatient: Patient = {
      id: 'pat-' + Date.now(),
      fullName: fullName.trim(),
      dni: cleanDni,
      birthDate,
      age: Number(age) || 30,
      gender,
      phone: phone.trim(),
      email: email.trim(),
      address: address.trim(),
      bloodType,
      insuranceProvider,
      policyNumber: insurancePolicyNumber || 'POL-' + Date.now().toString().slice(-6),
      portalPin: autoGeneratedPin,
      portalAccessCode: autoAccessCode,
      emergencyContact: {
        name: emergencyContactName || 'Familiar Directo',
        relation: 'Contacto de Emergencia',
        phone: emergencyContactPhone || phone,
      },
      safetyProfile: {
        allergies,
        contrastAllergyHistory: priorAdverseReactionToContrast,
        hasPacemaker,
        hasMetalImplants,
        hasAneurysmClips: false,
        isPregnantOrPossible,
        hasClaustrophobia,
        creatinineLevel,
        eGFR,
        diabeticOnMetformin,
        lastSafetyCheckDate: new Date().toISOString().split('T')[0],
      },
      createdAt: new Date().toISOString().split('T')[0],
      totalStudiesCount: 0,
    };

    onSavePatient(newPatient);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs select-none">
      <div className="bg-white border border-slate-200 rounded-3xl w-full max-w-3xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="p-4 bg-slate-50 border-b border-slate-200 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="p-2 bg-cyan-50 border border-cyan-200 rounded-xl text-cyan-700">
              <UserPlus className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">Registrar Nuevo Paciente</h3>
              <p className="text-xs text-slate-500">Ficha clínica de filiación y perfil de seguridad radiológica</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-slate-700 hover:bg-slate-100 rounded-lg transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="p-5 flex-1 overflow-y-auto space-y-4 text-xs text-slate-700">
          {/* Personal Demographic Data */}
          <div>
            <h4 className="font-bold text-slate-900 text-xs mb-2 flex items-center gap-1.5">
              <HeartPulse className="w-4 h-4 text-cyan-600" />
              <span>Datos Personales y Contacto</span>
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div className="sm:col-span-2">
                <label className="block text-slate-600 mb-1 font-semibold">Nombre Completo y Apellidos *</label>
                <input
                  type="text"
                  required
                  placeholder="ej. Dra. Elena Quispe Ramos"
                  value={fullName}
                  onChange={e => setFullName(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 rounded-xl p-2.5 text-slate-900 focus:outline-none focus:bg-white focus:border-cyan-600"
                />
              </div>
              <div>
                <label className="block text-slate-600 mb-1 font-semibold">DNI / Cédula *</label>
                <input
                  type="text"
                  required
                  placeholder="ej. 45892104"
                  value={dni}
                  onChange={e => setDni(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 rounded-xl p-2.5 text-slate-900 focus:outline-none focus:bg-white focus:border-cyan-600"
                />
              </div>
              <div>
                <label className="block text-slate-600 mb-1 font-semibold">Edad</label>
                <input
                  type="number"
                  value={age}
                  onChange={e => setAge(Number(e.target.value))}
                  className="w-full bg-slate-50 border border-slate-200 rounded-xl p-2.5 text-slate-900 focus:outline-none focus:bg-white focus:border-cyan-600"
                />
              </div>
              <div>
                <label className="block text-slate-600 mb-1 font-semibold">Género</label>
                <select
                  value={gender}
                  onChange={e => setGender(e.target.value as any)}
                  className="w-full bg-slate-50 border border-slate-200 rounded-xl p-2.5 text-slate-900 focus:outline-none focus:bg-white focus:border-cyan-600"
                >
                  <option value="M">Masculino</option>
                  <option value="F">Femenino</option>
                  <option value="OTRO">Otro / No especifica</option>
                </select>
              </div>
              <div>
                <label className="block text-slate-600 mb-1 font-semibold">Teléfono Móvil</label>
                <input
                  type="text"
                  placeholder="+51 987 654 321"
                  value={phone}
                  onChange={e => setPhone(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 rounded-xl p-2.5 text-slate-900 focus:outline-none focus:bg-white focus:border-cyan-600"
                />
              </div>
              <div className="sm:col-span-2">
                <label className="block text-slate-600 mb-1 font-semibold">Correo Electrónico</label>
                <input
                  type="email"
                  placeholder="paciente@correo.com"
                  value={email}
                  onChange={e => setEmail(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 rounded-xl p-2.5 text-slate-900 focus:outline-none focus:bg-white focus:border-cyan-600"
                />
              </div>
              <div>
                <label className="block text-slate-600 mb-1 font-semibold">Seguro Médico / EPS</label>
                <input
                  type="text"
                  placeholder="ej. Pacífico EPS / Rímac"
                  value={insuranceProvider}
                  onChange={e => setInsuranceProvider(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 rounded-xl p-2.5 text-slate-900 focus:outline-none focus:bg-white focus:border-cyan-600"
                />
              </div>
            </div>
          </div>

          {/* Safety & Contraindications Profile */}
          <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200 space-y-3">
            <h4 className="font-bold text-slate-900 text-xs flex items-center gap-1.5">
              <ShieldAlert className="w-4 h-4 text-amber-600" />
              <span>Perfil de Seguridad Radiológica y Alergias</span>
            </h4>

            <div>
              <label className="block text-slate-600 mb-1 font-semibold">
                Alergias conocidas (separar por comas):
              </label>
              <input
                type="text"
                placeholder="ej. Yodo, Penicilina, Mariscos, Ninguna"
                value={allergiesStr}
                onChange={e => setAllergiesStr(e.target.value)}
                className="w-full bg-white border border-slate-200 rounded-xl p-2.5 text-slate-900 focus:outline-none focus:border-amber-400"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
              <div>
                <label className="block text-slate-500 text-[11px]">Creatinina Sérica (mg/dL)</label>
                <input
                  type="number"
                  step="0.01"
                  value={creatinineLevel}
                  onChange={e => setCreatinineLevel(Number(e.target.value))}
                  className="w-full bg-white border border-slate-200 rounded-xl p-2 text-slate-900"
                />
              </div>
              <div>
                <label className="block text-slate-500 text-[11px]">eGFR Estimada (mL/min/1.73m²)</label>
                <input
                  type="number"
                  value={eGFR}
                  onChange={e => setEGFR(Number(e.target.value))}
                  className="w-full bg-white border border-slate-200 rounded-xl p-2 text-slate-900"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-2 text-xs">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={hasPacemaker}
                  onChange={e => setHasPacemaker(e.target.checked)}
                  className="rounded border-slate-300 text-amber-600 focus:ring-0"
                />
                <span className="font-semibold text-slate-700">Portador de Marcapasos</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={hasMetalImplants}
                  onChange={e => setHasMetalImplants(e.target.checked)}
                  className="rounded border-slate-300 text-amber-600 focus:ring-0"
                />
                <span className="font-semibold text-slate-700">Prótesis / Implantes Metálicos</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={isPregnantOrPossible}
                  onChange={e => setIsPregnantOrPossible(e.target.checked)}
                  className="rounded border-slate-300 text-amber-600 focus:ring-0"
                />
                <span className="font-semibold text-slate-700">Embarazo / Posible Gestación</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={hasClaustrophobia}
                  onChange={e => setHasClaustrophobia(e.target.checked)}
                  className="rounded border-slate-300 text-amber-600 focus:ring-0"
                />
                <span className="font-semibold text-slate-700">Claustrofobia Severa</span>
              </label>
            </div>

            {/* Auto Credentials Info Banner */}
            <div className="mt-3 p-3 bg-cyan-50 border border-cyan-200 rounded-xl text-[11px] text-cyan-900 flex items-center gap-2">
              <span className="text-base">🔑</span>
              <div>
                <strong>Acceso Automático al Expediente:</strong> Al guardar se generará automáticamente el <strong>Usuario (DNI)</strong> y <strong>Contraseña (PIN)</strong> para que el paciente consulte sus estudios en línea.
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="p-4 bg-slate-50 -mx-5 -mb-5 border-t border-slate-200 flex items-center justify-between mt-4">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 bg-white hover:bg-slate-100 text-slate-700 border border-slate-200 rounded-xl text-xs font-semibold transition-colors cursor-pointer shadow-xs"
            >
              Cancelar
            </button>
            <button
              type="submit"
              className="flex items-center gap-1.5 px-5 py-2.5 bg-cyan-600 hover:bg-cyan-700 text-white rounded-xl text-xs font-bold shadow-xs transition-all cursor-pointer"
            >
              <UserPlus className="w-4 h-4" />
              <span>Guardar Ficha del Paciente</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
